deepspeed --num_gpus=8 ./pretraining/contrastive_learning.py \
    --deepspeed "./ds_config_zero2.json" \
    --markdown_candidate_count 1024 \
    --pretrained_path "/data/zikun_workspace/checkpoints/pretraining/next_token_prediction" \
    --max_table_len 4096 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --dataloader_num_workers 32 \
    --learning_rate 1e-5 \
    --temperature 0.07 \
    --warmup_steps 100 \
    --weight_decay 0.01 \
    --num_train_epochs 5 \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_strategy "steps" \
    --eval_steps 100 \
    --save_total_limit 1 \
    --wandb_project "Contrastive_Learning" \
    --run_name "contrastive_learning_table_aug_markdown_bank_1d" \
    --output_dir "/data/zikun_workspace/checkpoints/pretraining/contrastive_learning"
