deepspeed --num_gpus=8 ./pretraining/task_query_classification.py \
    --deepspeed "./ds_config_zero2.json" \
    --dataset mimic_iv eicu ehrshot \
    --root_dir "/data/zikun_workspace/mimic-iv-3.1_tabular" \
    --train_sample_info_path "/data/zikun_workspace/mimic-iv-3.1_tabular/task_index/train" \
    --val_sample_info_path "/data/zikun_workspace/mimic-iv-3.1_tabular/task_index/val" \
    --table_text_embedding "/data/zikun_workspace/.cache/embeddings/mimic_iv/text_embeddings.pt" \
    --eicu_root_dir "/data/zikun_workspace/eicu-crd" \
    --eicu_processed_dir "/data/zikun_workspace/eicu-crd/processed" \
    --eicu_train_sample_info_path "/data/zikun_workspace/eicu-crd/processed/sample_info_train.json" \
    --eicu_val_sample_info_path "/data/zikun_workspace/eicu-crd/processed/sample_info_val.json" \
    --eicu_table_text_embedding "/data/zikun_workspace/.cache/embeddings/eicu/text_embeddings_stage2.pt" \
    --ehrshot_root_dir "/data/EHR_data_public/EHRSHOT" \
    --ehrshot_train_sample_info_path "/data/EHR_data_public/EHRSHOT/index/ehrshot_train.csv" \
    --ehrshot_val_sample_info_path "/data/EHR_data_public/EHRSHOT/index/ehrshot_val.csv" \
    --ehrshot_table_text_embedding "/data/zikun_workspace/.cache/embeddings/ehrshot/text_embeddings_stage2.pt" \
    --pretrained_path "/data/zikun_workspace/checkpoints/pretraining/contrastive_learning" \
    --query_embedding_cache "/data/zikun_workspace/.cache/embeddings/task_query_classification/task_query_llm_embeddings.pt" \
    --max_table_len 16384 \
    --per_device_train_batch_size 64 \
    --per_device_eval_batch_size 64 \
    --gradient_accumulation_steps 1 \
    --dataloader_num_workers 32 \
    --learning_rate 1e-5 \
    --warmup_steps 100 \
    --weight_decay 0.01 \
    --num_train_epochs 10 \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_strategy "steps" \
    --eval_steps 100 \
    --early_stopping_patience 10 \
    --wandb_project "Task_Query_Classification" \
    --run_name "task_query_classification_stage3" \
    --output_dir "/data/zikun_workspace/checkpoints/pretraining/task_query_classification" \
    --max_train_samples 180000
