deepspeed --num_gpus=8 ./pretraining/task_query_classification.py \
    --deepspeed "./ds_config_zero2.json" \
    --max_table_len 16384 \
    --per_device_train_batch_size 64 \
    --per_device_eval_batch_size 64 \
    --gradient_accumulation_steps 1 \
    --dataloader_num_workers 32 \
    --learning_rate 1e-5 \
    --warmup_steps 100 \
    --weight_decay 0.01 \
    --num_train_epochs 10 \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_strategy "steps" \
    --eval_steps 100 \
    --early_stopping_patience 10 \
    --wandb_project "Task_Query_Classification" \
    --run_name "task_query_classification_stage3" \
    --output_dir "/data/zikun_workspace/checkpoints/pretraining/task_query_classification" \
    --max_train_samples 180000
