"""
==============================================================================
STEP 5 of 5: Generate eICU Text Embedding Cache
==============================================================================

Purpose:
    Collect unique textual tokens from structured eICU tables and encode them
    with a Transformer model to build a reusable embedding cache.

Input:
    - sample_info_train.json / sample_info_val.json / sample_info_test.json
    - processed/patients/{patientunitstayid}/* generated by 4_partition_patients.py

Output:
    - text_embeddings.pt (embedding cache)

Usage:
    python 5_generate_embeddings.py

Prerequisites:
    Must run 3_generate_sample_info.py and 4_partition_patients.py first.

==============================================================================
"""
import os
import sys
import torch
import multiprocessing
from tqdm import tqdm
from transformers import AutoModel, AutoTokenizer
import pandas as pd
from multiprocessing import Pool

# Add project root
project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(project_root)

from dataset.eicu.eicu_dataset import EICUDataset

GLOBAL_DATASET = None

def init_worker(root, info, split):
    global GLOBAL_DATASET
    GLOBAL_DATASET = EICUDataset(
        root_dir=root,
        sample_info_path=info,
        split=split,
        task_name='all',
        lazy_mode=True,
        return_table=True,
        shuffle=False
    )

def process_sample(idx):
    try:
        sample = GLOBAL_DATASET._process_item(idx)
        df = sample.get('measurement_table')
            
        unique_local = set()
        
        if df is not None and not df.empty:
            # Collect Item texts
            if 'Item' in df.columns:
                unique_local.update(df['Item'].dropna().astype(str).unique())
            
            # Collect Value texts (non-numeric only)
            if 'Value' in df.columns:
                for val in df['Value'].dropna().astype(str).unique():
                    try:
                        float(val)
                    except ValueError:
                        unique_local.add(val)
            
            # Collect Unit texts
            if 'Unit' in df.columns:
                unique_local.update(df['Unit'].fillna('-').astype(str).unique())
                
        return unique_local
    except Exception as e:
        return set()

def main():
    # Configuration
    BERT_MODEL = "/home/ma-user/sfs_turbo/sai6/zkwan/model_weights/PubMedBERT"
    OUTPUT_PATH = "/home/ma-user/sfs_turbo/sai6/zkwan/.cache/embeddings/eicu/text_embeddings.pt"
    BATCH_SIZE = 256
    MAX_TOKEN_LEN = 512
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    
    print(f"Device: {DEVICE}")
    print(f"BERT Model: {BERT_MODEL}")
    print(f"Output: {OUTPUT_PATH}")
    
    # 1. Collect all unique texts from dataset
    print("\n" + "="*50)
    print("Collecting unique texts from eICU datasets using Multiprocessing...")
    print("="*50)
    
    unique_texts = set()
    base_dir = "/home/ma-user/sfs_turbo/sai6/zkwan/eicu-crd/processed"
    root_dir = "/home/ma-user/sfs_turbo/Data/eicu-crd/2.0"
    
    splits = {
        'train': os.path.join(base_dir, "sample_info_train.json"),
        'val': os.path.join(base_dir, "sample_info_val.json"),
        'test': os.path.join(base_dir, "sample_info_test.json")
    }
    
    for split_name, info_path in splits.items():
        if not os.path.exists(info_path):
            print(f"Skipping {split_name}, file not found: {info_path}")
            continue
            
        print(f"\nProcessing {split_name} split...")
        temp_dataset = EICUDataset(
            root_dir=root_dir,
            sample_info_path=info_path,
            split=split_name,
            task_name='all',
            lazy_mode=True,
            return_table=False,
            shuffle=False
        )
        total_samples = len(temp_dataset.sample_info)
        print(f"Found {total_samples} samples.")
        
        num_workers = min(32, multiprocessing.cpu_count())
        with Pool(processes=num_workers, initializer=init_worker, initargs=(root_dir, info_path, split_name)) as pool:
            results = list(tqdm(pool.imap_unordered(process_sample, range(total_samples), chunksize=100), total=total_samples))
            
            for res in results:
                if res:
                    unique_texts.update(res)

    # Add special tokens
    unique_texts.update(['[PAD]', '[EMPTY]', '-', '0'])
    unique_texts = list(unique_texts)
    print(f"\nTotal unique texts: {len(unique_texts)}")
    
    # 2. Load tokenizer and model
    print("\nLoading BERT model...")
    tokenizer = AutoTokenizer.from_pretrained(BERT_MODEL)
    model = AutoModel.from_pretrained(BERT_MODEL)
    
    # Multi-GPU support
    if torch.cuda.is_available():
        if torch.cuda.device_count() > 1:
            print(f"Using {torch.cuda.device_count()} GPUs for encoding!")
            model = torch.nn.DataParallel(model)
        model = model.to(DEVICE)
    model.eval()
    
    for param in model.parameters():
        param.requires_grad = False
    
    # Get config handle (DataParallel wraps the model in .module)
    if hasattr(model, "module"):
        text_dim = model.module.config.hidden_size
    else:
        text_dim = model.config.hidden_size
    print(f"Text embedding dimension: {text_dim}")

    # 3. Encode all unique texts with BERT
    print("\n" + "="*50)
    print("Encoding texts with BERT...")
    print("="*50)
    
    embeddings_dict = {}
    
    class TextDataset(torch.utils.data.Dataset):
        def __init__(self, texts):
            self.texts = texts
        def __len__(self):
            return len(self.texts)
        def __getitem__(self, idx):
            return self.texts[idx]

    dataset = TextDataset(unique_texts)
    # Increase batch size if using multiple GPUs
    effective_batch_size = BATCH_SIZE * max(1, torch.cuda.device_count())
    dataloader = torch.utils.data.DataLoader(dataset, batch_size=effective_batch_size, shuffle=False, num_workers=4)
    
    with torch.no_grad():
        for batch_texts in tqdm(dataloader, desc="Encoding batches"):
            tokens = tokenizer(
                list(batch_texts),
                padding='max_length',
                truncation=True,
                max_length=MAX_TOKEN_LEN,
                return_tensors='pt'
            ).to(DEVICE)
            
            out = model(**tokens)
            embs = out.last_hidden_state[:, 0, :]  # CLS token
            
            # Store on CPU
            for j, text in enumerate(batch_texts):
                embeddings_dict[text] = embs[j].cpu()
    
    print(f"Encoded {len(embeddings_dict)} unique texts")
    
    # 4. Save cache
    print(f"\nSaving to {OUTPUT_PATH}...")
    torch.save({
        'embeddings': embeddings_dict,
        'text_dim': text_dim,
        'bert_model': BERT_MODEL,
    }, OUTPUT_PATH)
    
    # Stats
    file_size = os.path.getsize(OUTPUT_PATH) / (1024 * 1024)
    print(f"Cache file size: {file_size:.2f} MB")
    print("Done!")

if __name__ == "__main__":
    main()
